# Generated by Django 3.0.6 on 2020-05-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CC', 'Padrão'), ('CI', 'Investimento')], default='CC', max_length=2)),
                ('description', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], default='A', max_length=1)),
                ('default', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], default='C', max_length=1)),
                ('description', models.CharField(max_length=50)),
                ('createOn', models.DateTimeField()),
                ('settlementOn', models.DateTimeField(null=True)),
                ('account', models.IntegerField()),
                ('subGroup', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('L', 'Liquidado')], default='A', max_length=1)),
                ('transferId', models.IntegerField(null=True)),
            ],
        ),
    ]
