# Generated by Django 3.0.6 on 2020-05-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.Group'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.SubGroup'),
        ),
    ]
