# Generated by Django 3.0.6 on 2020-05-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200515_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='settlementOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transferId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
